site_name: 'Awesome DevOps Jobs'
site_url: 'https://awesome-devops-jobs.com'
site_description: 'A curated list of awesome DevOps Jobs'
site_author: 'Andy Boutte'
repo_name: 'aboutte/awesome-devops-jobs'
repo_url: 'https://github.com/aboutte/awesome-devops-jobs'
theme: 'material'
extra:
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'pink'
  social:
    - type: 'github'
      link: 'https://github.com/aboutte'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/aboutte'
google_analytics:
  - 'UA-111280757-1'
  - 'auto'
pages:
  - "Life is short, you need DevOps.": "index.md"
